import type { SpeciesId } from '../doc/types.js';
import type { PlantCat, Species } from './types.js';

/**
 * Swedish hardiness zones run 1 (Skåne coast) to 8 (mountain birch belt), so
 * `zone` here is the highest zone the plant is reliably hardy in. For annual
 * vegetables it is the highest zone where the crop ripens outdoors.
 */
export const SPECIES: readonly Species[] = [
	{
		id: 'bjork',
		latin: 'Betula pendula',
		sv: 'Vårtbjörk',
		en: 'Silver birch',
		cat: 'tree',
		form: 'weeping',
		mature: { h: 20, w: 9 },
		growthRate: 12,
		evergreen: false,
		foliage: { spring: '#a8c95f', summer: '#6d9440', autumn: '#e6c74e', winter: null },
		bark: '#e6e3d8',
		bloom: { colour: '#b9ad6a', months: [4, 5], size: 0.05 },
		needs: { sun: 'full', moisture: 'normal', zone: 7 },
		spacing: 8
	},
	{
		id: 'ronn',
		latin: 'Sorbus aucuparia',
		sv: 'Rönn',
		en: 'Rowan',
		cat: 'tree',
		form: 'broadleaf-round',
		mature: { h: 10, w: 6 },
		growthRate: 10,
		evergreen: false,
		foliage: { spring: '#8fb85c', summer: '#557f3e', autumn: '#c8492c', winter: null },
		bark: '#6f6a5e',
		bloom: { colour: '#f2efe0', months: [5, 6], size: 0.12 },
		fruit: { colour: '#d1391f', months: [8, 9, 10] },
		needs: { sun: 'full', moisture: 'normal', zone: 8 },
		spacing: 5
	},
	{
		id: 'oxel',
		latin: 'Sorbus intermedia',
		sv: 'Oxel',
		en: 'Swedish whitebeam',
		cat: 'tree',
		form: 'broadleaf-round',
		mature: { h: 12, w: 8 },
		growthRate: 12,
		evergreen: false,
		foliage: { spring: '#93b46a', summer: '#4f7539', autumn: '#b5893a', winter: null },
		bark: '#655f55',
		bloom: { colour: '#f0ecdb', months: [5, 6], size: 0.1 },
		fruit: { colour: '#c2442a', months: [9, 10] },
		needs: { sun: 'full', moisture: 'normal', zone: 6 },
		spacing: 7
	},
	{
		id: 'appeltrad',
		latin: 'Malus domestica',
		sv: 'Äppelträd',
		en: 'Apple',
		cat: 'tree',
		form: 'broadleaf-spreading',
		mature: { h: 5, w: 5 },
		growthRate: 8,
		evergreen: false,
		foliage: { spring: '#96b95e', summer: '#5c8442', autumn: '#c9a63c', winter: null },
		bark: '#6a5b4a',
		bloom: { colour: '#f6dfe2', months: [5], size: 0.05 },
		fruit: { colour: '#c33a2c', months: [8, 9, 10] },
		needs: { sun: 'full', moisture: 'normal', zone: 5 },
		spacing: 5
	},
	{
		id: 'korsbar',
		latin: 'Prunus avium',
		sv: 'Sötkörsbär',
		en: 'Sweet cherry',
		cat: 'tree',
		form: 'broadleaf-round',
		mature: { h: 8, w: 6 },
		growthRate: 9,
		evergreen: false,
		foliage: { spring: '#8fb45c', summer: '#4e7a3c', autumn: '#d2652f', winter: null },
		bark: '#7c4a3c',
		bloom: { colour: '#fbf4f0', months: [5], size: 0.04 },
		fruit: { colour: '#8f1f2c', months: [7, 8] },
		needs: { sun: 'full', moisture: 'normal', zone: 4 },
		spacing: 6
	},
	{
		id: 'plommon',
		latin: 'Prunus domestica',
		sv: 'Plommon',
		en: 'Plum',
		cat: 'tree',
		form: 'broadleaf-round',
		mature: { h: 5, w: 4 },
		growthRate: 7,
		evergreen: false,
		foliage: { spring: '#8db35c', summer: '#4d7a3d', autumn: '#c8952f', winter: null },
		bark: '#6b4c3d',
		bloom: { colour: '#fbf6ee', months: [4, 5], size: 0.035 },
		fruit: { colour: '#5a3a6b', months: [8, 9] },
		needs: { sun: 'full', moisture: 'normal', zone: 4 },
		spacing: 4.5
	},
	{
		id: 'paron',
		latin: 'Pyrus communis',
		sv: 'Päron',
		en: 'Pear',
		cat: 'tree',
		form: 'broadleaf-round',
		mature: { h: 7, w: 4.5 },
		growthRate: 10,
		evergreen: false,
		foliage: { spring: '#8db45e', summer: '#4b7539', autumn: '#c0553a', winter: null },
		bark: '#5f5348',
		bloom: { colour: '#fbfaf4', months: [5], size: 0.04 },
		fruit: { colour: '#c2b357', months: [9, 10] },
		needs: { sun: 'full', moisture: 'normal', zone: 4 },
		spacing: 5
	},
	{
		id: 'hagg',
		latin: 'Prunus padus',
		sv: 'Hägg',
		en: 'Bird cherry',
		cat: 'tree',
		form: 'broadleaf-round',
		mature: { h: 10, w: 7 },
		growthRate: 9,
		evergreen: false,
		foliage: { spring: '#93bc5f', summer: '#4f7c3c', autumn: '#c07a35', winter: null },
		bark: '#5a4b40',
		bloom: { colour: '#f7f4e6', months: [5], size: 0.1 },
		fruit: { colour: '#2b1d1b', months: [7, 8] },
		needs: { sun: 'part', moisture: 'moist', zone: 8 },
		spacing: 6
	},
	{
		id: 'haggmispel',
		latin: 'Amelanchier lamarckii',
		sv: 'Prakthäggmispel',
		en: 'Snowy mespilus',
		cat: 'tree',
		form: 'multi-stem',
		mature: { h: 6, w: 5 },
		growthRate: 8,
		evergreen: false,
		foliage: { spring: '#a5bd77', summer: '#4f7c40', autumn: '#d4542a', winter: null },
		bark: '#645649',
		bloom: { colour: '#fbf8f2', months: [4, 5], size: 0.06 },
		fruit: { colour: '#3b2a44', months: [7, 8] },
		needs: { sun: 'part', moisture: 'normal', zone: 5 },
		spacing: 4
	},
	{
		id: 'lind',
		latin: 'Tilia cordata',
		sv: 'Skogslind',
		en: 'Small-leaved lime',
		cat: 'tree',
		form: 'broadleaf-round',
		mature: { h: 20, w: 12 },
		growthRate: 20,
		evergreen: false,
		foliage: { spring: '#9cc25e', summer: '#4d7a3a', autumn: '#e0bd45', winter: null },
		bark: '#5c5247',
		bloom: { colour: '#e4dd9a', months: [7], size: 0.05 },
		needs: { sun: 'full', moisture: 'normal', zone: 5 },
		spacing: 10
	},
	{
		id: 'lonn',
		latin: 'Acer platanoides',
		sv: 'Skogslönn',
		en: 'Norway maple',
		cat: 'tree',
		form: 'broadleaf-round',
		mature: { h: 20, w: 14 },
		growthRate: 18,
		evergreen: false,
		foliage: { spring: '#96c05a', summer: '#487538', autumn: '#e09a2b', winter: null },
		bark: '#584f45',
		bloom: { colour: '#c8d45c', months: [5], size: 0.05 },
		needs: { sun: 'part', moisture: 'normal', zone: 5 },
		spacing: 11
	},
	{
		id: 'salg',
		latin: 'Salix caprea',
		sv: 'Sälg',
		en: 'Goat willow',
		cat: 'tree',
		form: 'multi-stem',
		mature: { h: 10, w: 7 },
		growthRate: 7,
		evergreen: false,
		foliage: { spring: '#93aa63', summer: '#556f3f', autumn: '#c3a842', winter: null },
		bark: '#6b6a58',
		bloom: { colour: '#e5d67a', months: [3, 4], size: 0.04 },
		needs: { sun: 'full', moisture: 'moist', zone: 8 },
		spacing: 6
	},
	{
		id: 'ek',
		latin: 'Quercus robur',
		sv: 'Ek',
		en: 'English oak',
		cat: 'tree',
		form: 'broadleaf-spreading',
		mature: { h: 22, w: 18 },
		growthRate: 30,
		evergreen: false,
		foliage: { spring: '#93b862', summer: '#46703a', autumn: '#9c7a3f', winter: null },
		bark: '#5c5348',
		bloom: { colour: '#b9c06a', months: [5], size: 0.03 },
		fruit: { colour: '#7a5a2e', months: [9, 10] },
		needs: { sun: 'full', moisture: 'normal', zone: 4 },
		spacing: 14
	},
	{
		id: 'pelarek',
		latin: 'Quercus robur f. fastigiata',
		sv: 'Pelarek',
		en: 'Columnar oak',
		cat: 'tree',
		form: 'columnar',
		mature: { h: 15, w: 4 },
		growthRate: 22,
		evergreen: false,
		foliage: { spring: '#93b862', summer: '#46703a', autumn: '#9c7a3f', winter: null },
		bark: '#5c5348',
		fruit: { colour: '#7a5a2e', months: [9, 10] },
		needs: { sun: 'full', moisture: 'normal', zone: 3 },
		spacing: 3.5
	},
	{
		id: 'bok',
		latin: 'Fagus sylvatica',
		sv: 'Bok',
		en: 'Beech',
		cat: 'tree',
		form: 'broadleaf-round',
		mature: { h: 22, w: 15 },
		growthRate: 25,
		evergreen: false,
		foliage: { spring: '#a6c364', summer: '#40682f', autumn: '#a9622c', winter: null },
		bark: '#8d8a80',
		fruit: { colour: '#84623a', months: [9, 10] },
		needs: { sun: 'part', moisture: 'normal', zone: 3 },
		spacing: 12
	},
	{
		id: 'asp',
		latin: 'Populus tremula',
		sv: 'Asp',
		en: 'Aspen',
		cat: 'tree',
		form: 'broadleaf-round',
		mature: { h: 20, w: 8 },
		growthRate: 11,
		evergreen: false,
		foliage: { spring: '#9cbd66', summer: '#5c8248', autumn: '#eec53f', winter: null },
		bark: '#a9aa98',
		bloom: { colour: '#8f7f6a', months: [4], size: 0.06 },
		needs: { sun: 'full', moisture: 'normal', zone: 8 },
		spacing: 7
	},
	{
		id: 'avenbok',
		latin: 'Carpinus betulus',
		sv: 'Avenbok',
		en: 'Hornbeam',
		cat: 'tree',
		form: 'broadleaf-round',
		mature: { h: 15, w: 10 },
		growthRate: 16,
		evergreen: false,
		foliage: { spring: '#9bc063', summer: '#4a7538', autumn: '#c9a63f', winter: null },
		bark: '#7c7a70',
		fruit: { colour: '#b6a06a', months: [9, 10] },
		needs: { sun: 'part', moisture: 'normal', zone: 3 },
		spacing: 9
	},
	{
		id: 'hassel',
		latin: 'Corylus avellana',
		sv: 'Hassel',
		en: 'Hazel',
		cat: 'tree',
		form: 'multi-stem',
		mature: { h: 5, w: 5 },
		growthRate: 7,
		evergreen: false,
		foliage: { spring: '#9cbc63', summer: '#527d3e', autumn: '#d8b23f', winter: null },
		bark: '#6a5b4c',
		bloom: { colour: '#d9cf78', months: [3, 4], size: 0.06 },
		fruit: { colour: '#a97f45', months: [9] },
		needs: { sun: 'part', moisture: 'normal', zone: 4 },
		spacing: 4
	},
	{
		id: 'japansklonn',
		latin: 'Acer palmatum',
		sv: 'Japansk lönn',
		en: 'Japanese maple',
		cat: 'tree',
		form: 'multi-stem',
		mature: { h: 4, w: 4 },
		growthRate: 10,
		evergreen: false,
		foliage: { spring: '#b4632f', summer: '#8a4a35', autumn: '#c8321f', winter: null },
		bark: '#6b5348',
		needs: { sun: 'part', moisture: 'normal', zone: 2 },
		spacing: 3.5
	},
	{
		id: 'magnolia',
		latin: 'Magnolia stellata',
		sv: 'Stjärnmagnolia',
		en: 'Star magnolia',
		cat: 'tree',
		form: 'multi-stem',
		mature: { h: 3, w: 3 },
		growthRate: 10,
		evergreen: false,
		foliage: { spring: '#8fb45f', summer: '#4d7a40', autumn: '#c2a248', winter: null },
		bark: '#6f6459',
		bloom: { colour: '#f7f1ea', months: [4, 5], size: 0.1 },
		needs: { sun: 'part', moisture: 'normal', zone: 2 },
		spacing: 3
	},
	{
		id: 'tall',
		latin: 'Pinus sylvestris',
		sv: 'Tall',
		en: 'Scots pine',
		cat: 'conifer',
		form: 'conifer-spire',
		mature: { h: 22, w: 9 },
		growthRate: 20,
		evergreen: true,
		foliage: { spring: '#5c7a58', summer: '#4d6b4c', autumn: '#4a6749', winter: '#455f46' },
		bark: '#a06a3c',
		fruit: { colour: '#6b5942', months: [9, 10, 11] },
		needs: { sun: 'full', moisture: 'dry', zone: 8 },
		spacing: 7
	},
	{
		id: 'gran',
		latin: 'Picea abies',
		sv: 'Gran',
		en: 'Norway spruce',
		cat: 'conifer',
		form: 'conifer-spire',
		mature: { h: 25, w: 7 },
		growthRate: 18,
		evergreen: true,
		foliage: { spring: '#5f8a52', summer: '#3b5f42', autumn: '#375a3f', winter: '#33543b' },
		bark: '#4d4038',
		fruit: { colour: '#7a5a44', months: [9, 10] },
		needs: { sun: 'part', moisture: 'moist', zone: 8 },
		spacing: 6
	},
	{
		id: 'en',
		latin: 'Juniperus communis',
		sv: 'En',
		en: 'Common juniper',
		cat: 'conifer',
		form: 'columnar',
		mature: { h: 5, w: 1.4 },
		growthRate: 14,
		evergreen: true,
		foliage: { spring: '#63806a', summer: '#4f6d5c', autumn: '#4c6a5a', winter: '#496657' },
		bark: '#6a5748',
		fruit: { colour: '#3d4f63', months: [9, 10, 11] },
		needs: { sun: 'full', moisture: 'dry', zone: 8 },
		spacing: 1.5
	},
	{
		id: 'bergtall',
		latin: 'Pinus mugo',
		sv: 'Bergtall',
		en: 'Mountain pine',
		cat: 'conifer',
		form: 'conifer-globe',
		mature: { h: 2.5, w: 3 },
		growthRate: 12,
		evergreen: true,
		foliage: { spring: '#587a52', summer: '#456745', autumn: '#436443', winter: '#3f6041' },
		bark: '#5f4c3d',
		needs: { sun: 'full', moisture: 'dry', zone: 8 },
		spacing: 2.5
	},
	{
		id: 'serbgran',
		latin: 'Picea omorika',
		sv: 'Serbgran',
		en: 'Serbian spruce',
		cat: 'conifer',
		form: 'conifer-spire',
		mature: { h: 15, w: 4 },
		growthRate: 15,
		evergreen: true,
		foliage: { spring: '#5c8060', summer: '#42654f', autumn: '#40634e', winter: '#3d604c' },
		bark: '#584a3f',
		fruit: { colour: '#5a4a54', months: [9, 10] },
		needs: { sun: 'full', moisture: 'normal', zone: 6 },
		spacing: 4
	},
	{
		id: 'blagran',
		latin: 'Picea pungens',
		sv: 'Blågran',
		en: 'Blue spruce',
		cat: 'conifer',
		form: 'conifer-spire',
		mature: { h: 14, w: 5 },
		growthRate: 15,
		evergreen: true,
		foliage: { spring: '#8fa8ae', summer: '#7d9aa0', autumn: '#7a979e', winter: '#76939b' },
		bark: '#57493e',
		needs: { sun: 'full', moisture: 'normal', zone: 6 },
		spacing: 5
	},
	{
		id: 'lark',
		latin: 'Larix decidua',
		sv: 'Europeisk lärk',
		en: 'European larch',
		cat: 'conifer',
		form: 'conifer-spire',
		mature: { h: 25, w: 8 },
		growthRate: 14,
		evergreen: false,
		foliage: { spring: '#9dbd5c', summer: '#5f8a4a', autumn: '#dcae3c', winter: null },
		bark: '#6b5343',
		fruit: { colour: '#8a6a4e', months: [9, 10] },
		needs: { sun: 'full', moisture: 'normal', zone: 6 },
		spacing: 7
	},
	{
		id: 'idegran',
		latin: 'Taxus baccata',
		sv: 'Idegran',
		en: 'English yew',
		cat: 'conifer',
		form: 'conifer-globe',
		mature: { h: 4, w: 3.5 },
		growthRate: 18,
		evergreen: true,
		foliage: { spring: '#41654a', summer: '#2f4f3a', autumn: '#2e4d39', winter: '#2b4936' },
		bark: '#6b4c3f',
		fruit: { colour: '#c8322c', months: [9, 10] },
		needs: { sun: 'shade', moisture: 'normal', zone: 3 },
		spacing: 3
	},
	{
		id: 'thuja',
		latin: 'Thuja occidentalis',
		sv: 'Tuja',
		en: 'White cedar',
		cat: 'conifer',
		form: 'conifer-spire',
		mature: { h: 10, w: 3 },
		growthRate: 10,
		evergreen: true,
		foliage: { spring: '#6a8f56', summer: '#4f7549', autumn: '#4d7247', winter: '#6d7a4a' },
		bark: '#6b5344',
		needs: { sun: 'part', moisture: 'normal', zone: 5 },
		spacing: 2.5
	},
	{
		id: 'liguster',
		latin: 'Ligustrum vulgare',
		sv: 'Liguster',
		en: 'Wild privet',
		cat: 'hedge',
		form: 'hedge-run',
		mature: { h: 1.6, w: 0.6 },
		growthRate: 5,
		evergreen: false,
		foliage: { spring: '#6f9450', summer: '#3f6b3c', autumn: '#4a6b48', winter: null },
		bark: '#6b5c4b',
		bloom: { colour: '#f4f1e2', months: [6, 7], size: 0.06 },
		fruit: { colour: '#26232b', months: [9, 10, 11] },
		needs: { sun: 'part', moisture: 'normal', zone: 4 },
		spacing: 0.35
	},
	{
		id: 'hackoxbar',
		latin: 'Cotoneaster lucidus',
		sv: 'Häckoxbär',
		en: 'Hedge cotoneaster',
		cat: 'hedge',
		form: 'hedge-run',
		mature: { h: 1.8, w: 0.7 },
		growthRate: 5,
		evergreen: false,
		foliage: { spring: '#7fa855', summer: '#3f6b3a', autumn: '#c8492f', winter: null },
		bark: '#65543f',
		bloom: { colour: '#f0dedd', months: [6], size: 0.02 },
		fruit: { colour: '#231f24', months: [9, 10] },
		needs: { sun: 'full', moisture: 'normal', zone: 6 },
		spacing: 0.4
	},
	{
		id: 'mabar',
		latin: 'Ribes alpinum',
		sv: 'Måbär',
		en: 'Alpine currant',
		cat: 'hedge',
		form: 'hedge-run',
		mature: { h: 1.2, w: 0.6 },
		growthRate: 4,
		evergreen: false,
		foliage: { spring: '#8fbb5c', summer: '#527d3f', autumn: '#c9a63c', winter: null },
		bark: '#6f5f4c',
		bloom: { colour: '#c8cf7a', months: [5], size: 0.02 },
		fruit: { colour: '#c23a2c', months: [7, 8] },
		needs: { sun: 'shade', moisture: 'normal', zone: 7 },
		spacing: 0.35
	},
	{
		id: 'buxbom',
		latin: 'Buxus sempervirens',
		sv: 'Buxbom',
		en: 'Box',
		cat: 'hedge',
		form: 'hedge-run',
		mature: { h: 0.6, w: 0.4 },
		growthRate: 8,
		evergreen: true,
		foliage: { spring: '#4f7a44', summer: '#3d6639', autumn: '#3c6438', winter: '#3a5f37' },
		bark: '#7a6a52',
		needs: { sun: 'part', moisture: 'normal', zone: 2 },
		spacing: 0.25
	},
	{
		id: 'avenbokshack',
		latin: 'Carpinus betulus',
		sv: 'Avenbokshäck',
		en: 'Hornbeam hedge',
		cat: 'hedge',
		form: 'hedge-run',
		mature: { h: 2, w: 0.7 },
		growthRate: 6,
		evergreen: false,
		foliage: { spring: '#9bc063', summer: '#4a7538', autumn: '#c1913c', winter: null },
		bark: '#7c7a70',
		needs: { sun: 'part', moisture: 'normal', zone: 3 },
		spacing: 0.4
	},
	{
		id: 'hackhagtorn',
		latin: 'Crataegus monogyna',
		sv: 'Trubbhagtorn',
		en: 'Hawthorn',
		cat: 'hedge',
		form: 'hedge-run',
		mature: { h: 2.2, w: 0.8 },
		growthRate: 6,
		evergreen: false,
		foliage: { spring: '#8ab358', summer: '#47703a', autumn: '#b07a3a', winter: null },
		bark: '#655547',
		bloom: { colour: '#f7f2e6', months: [5, 6], size: 0.02 },
		fruit: { colour: '#b8302a', months: [9, 10] },
		needs: { sun: 'full', moisture: 'normal', zone: 5 },
		spacing: 0.4
	},
	{
		id: 'berberis',
		latin: 'Berberis thunbergii',
		sv: 'Häckberberis',
		en: 'Japanese barberry',
		cat: 'hedge',
		form: 'hedge-run',
		mature: { h: 1, w: 0.6 },
		growthRate: 5,
		evergreen: false,
		foliage: { spring: '#8a4a3f', summer: '#6f3a35', autumn: '#c4342a', winter: null },
		bark: '#7a5a3f',
		bloom: { colour: '#e5cf62', months: [5], size: 0.01 },
		fruit: { colour: '#c22a24', months: [9, 10, 11] },
		needs: { sun: 'full', moisture: 'dry', zone: 4 },
		spacing: 0.35
	},
	{
		id: 'syren',
		latin: 'Syringa vulgaris',
		sv: 'Syren',
		en: 'Common lilac',
		cat: 'shrub',
		form: 'multi-stem',
		mature: { h: 4.5, w: 3.5 },
		growthRate: 7,
		evergreen: false,
		foliage: { spring: '#7fa85a', summer: '#4d7845', autumn: '#6b7a44', winter: null },
		bark: '#6a6058',
		bloom: { colour: '#9d7fc0', months: [5, 6], size: 0.18 },
		needs: { sun: 'full', moisture: 'normal', zone: 6 },
		spacing: 3
	},
	{
		id: 'schersmin',
		latin: 'Philadelphus coronarius',
		sv: 'Doftschersmin',
		en: 'Mock orange',
		cat: 'shrub',
		form: 'shrub-mound',
		mature: { h: 3, w: 2.5 },
		growthRate: 6,
		evergreen: false,
		foliage: { spring: '#8fb85f', summer: '#4f7a3e', autumn: '#c9b348', winter: null },
		bark: '#6b5a48',
		bloom: { colour: '#fbf8ee', months: [6, 7], size: 0.05 },
		needs: { sun: 'part', moisture: 'normal', zone: 5 },
		spacing: 2.5
	},
	{
		id: 'hortensia',
		latin: 'Hydrangea macrophylla',
		sv: 'Trädgårdshortensia',
		en: 'Bigleaf hydrangea',
		cat: 'shrub',
		form: 'shrub-mound',
		mature: { h: 1.4, w: 1.4 },
		growthRate: 4,
		evergreen: false,
		foliage: { spring: '#7fb055', summer: '#3f6f3c', autumn: '#8a8f4e', winter: null },
		bark: '#7a6a55',
		bloom: { colour: '#8fa8d4', months: [7, 8, 9], size: 0.18 },
		needs: { sun: 'part', moisture: 'moist', zone: 2 },
		spacing: 1.2
	},
	{
		id: 'vipphortensia',
		latin: 'Hydrangea paniculata',
		sv: 'Vipphortensia',
		en: 'Panicle hydrangea',
		cat: 'shrub',
		form: 'shrub-mound',
		mature: { h: 2.5, w: 2 },
		growthRate: 5,
		evergreen: false,
		foliage: { spring: '#84b358', summer: '#44713c', autumn: '#8f8a4a', winter: null },
		bark: '#75634f',
		bloom: { colour: '#f4efe0', months: [7, 8, 9], size: 0.2 },
		needs: { sun: 'part', moisture: 'moist', zone: 5 },
		spacing: 1.8
	},
	{
		id: 'vresros',
		latin: 'Rosa rugosa',
		sv: 'Vresros',
		en: 'Rugosa rose',
		cat: 'shrub',
		form: 'shrub-mound',
		mature: { h: 1.6, w: 1.6 },
		growthRate: 4,
		evergreen: false,
		foliage: { spring: '#7fa855', summer: '#436f3a', autumn: '#c9a53c', winter: null },
		bark: '#6f5c46',
		bloom: { colour: '#c25a86', months: [6, 7, 8, 9], size: 0.08 },
		fruit: { colour: '#c8402a', months: [8, 9, 10] },
		needs: { sun: 'full', moisture: 'dry', zone: 7 },
		spacing: 1.2
	},
	{
		id: 'spirea',
		latin: 'Spiraea japonica',
		sv: 'Praktspirea',
		en: 'Japanese spiraea',
		cat: 'shrub',
		form: 'shrub-mound',
		mature: { h: 0.9, w: 1.1 },
		growthRate: 3,
		evergreen: false,
		foliage: { spring: '#a8bd52', summer: '#5c8440', autumn: '#c0722f', winter: null },
		bark: '#6f5c46',
		bloom: { colour: '#d0648c', months: [6, 7, 8], size: 0.08 },
		needs: { sun: 'full', moisture: 'normal', zone: 5 },
		spacing: 0.8
	},
	{
		id: 'brudspirea',
		latin: 'Spiraea x cinerea',
		sv: 'Brudspirea',
		en: 'Grey spiraea',
		cat: 'shrub',
		form: 'shrub-mound',
		mature: { h: 1.8, w: 2 },
		growthRate: 4,
		evergreen: false,
		foliage: { spring: '#93ad6a', summer: '#5f7f52', autumn: '#c2a04a', winter: null },
		bark: '#6b5a48',
		bloom: { colour: '#fbf7ef', months: [5], size: 0.04 },
		needs: { sun: 'full', moisture: 'normal', zone: 5 },
		spacing: 1.5
	},
	{
		id: 'rhododendron',
		latin: 'Rhododendron catawbiense',
		sv: 'Parkrhododendron',
		en: 'Catawba rhododendron',
		cat: 'shrub',
		form: 'shrub-mound',
		mature: { h: 2, w: 2.4 },
		growthRate: 8,
		evergreen: true,
		foliage: { spring: '#3f6b3f', summer: '#33593a', autumn: '#325738', winter: '#2f5236' },
		bark: '#5f4d3f',
		bloom: { colour: '#b06a9c', months: [5, 6], size: 0.16 },
		needs: { sun: 'part', moisture: 'moist', zone: 4 },
		spacing: 1.8
	},
	{
		id: 'azalea',
		latin: 'Rhododendron luteum',
		sv: 'Gul azalea',
		en: 'Yellow azalea',
		cat: 'shrub',
		form: 'shrub-mound',
		mature: { h: 1.8, w: 1.6 },
		growthRate: 7,
		evergreen: false,
		foliage: { spring: '#7fa855', summer: '#4a7340', autumn: '#c2482a', winter: null },
		bark: '#63513f',
		bloom: { colour: '#e8a92f', months: [5, 6], size: 0.06 },
		needs: { sun: 'part', moisture: 'moist', zone: 4 },
		spacing: 1.4
	},
	{
		id: 'benved',
		latin: 'Euonymus europaeus',
		sv: 'Benved',
		en: 'Spindle',
		cat: 'shrub',
		form: 'shrub-mound',
		mature: { h: 3, w: 2.5 },
		growthRate: 6,
		evergreen: false,
		foliage: { spring: '#87b25c', summer: '#487339', autumn: '#c04a55', winter: null },
		bark: '#5f5a4c',
		bloom: { colour: '#c4cf8a', months: [5, 6], size: 0.01 },
		fruit: { colour: '#d4577a', months: [9, 10] },
		needs: { sun: 'part', moisture: 'normal', zone: 5 },
		spacing: 2.2
	},
	{
		id: 'forsythia',
		latin: 'Forsythia x intermedia',
		sv: 'Praktforsythia',
		en: 'Forsythia',
		cat: 'shrub',
		form: 'shrub-mound',
		mature: { h: 2.2, w: 2 },
		growthRate: 4,
		evergreen: false,
		foliage: { spring: '#8fb757', summer: '#4d7a3c', autumn: '#a08a44', winter: null },
		bark: '#6b5a45',
		bloom: { colour: '#e8c31f', months: [4, 5], size: 0.03 },
		needs: { sun: 'full', moisture: 'normal', zone: 4 },
		spacing: 1.6
	},
	{
		id: 'kornell',
		latin: 'Cornus alba',
		sv: 'Rysk kornell',
		en: 'Red-barked dogwood',
		cat: 'shrub',
		form: 'shrub-mound',
		mature: { h: 2.5, w: 2.5 },
		growthRate: 4,
		evergreen: false,
		foliage: { spring: '#84ad5f', summer: '#4a7342', autumn: '#8f3b3a', winter: null },
		bark: '#a83a2c',
		bloom: { colour: '#f0ead6', months: [6], size: 0.05 },
		fruit: { colour: '#dfe2dc', months: [8, 9] },
		needs: { sun: 'part', moisture: 'moist', zone: 6 },
		spacing: 2
	},
	{
		id: 'olvon',
		latin: 'Viburnum opulus',
		sv: 'Olvon',
		en: 'Guelder rose',
		cat: 'shrub',
		form: 'shrub-mound',
		mature: { h: 3, w: 2.8 },
		growthRate: 5,
		evergreen: false,
		foliage: { spring: '#84b05c', summer: '#48743c', autumn: '#b8402c', winter: null },
		bark: '#655544',
		bloom: { colour: '#f7f4e8', months: [6], size: 0.1 },
		fruit: { colour: '#c8291f', months: [8, 9, 10] },
		needs: { sun: 'part', moisture: 'moist', zone: 6 },
		spacing: 2.5
	},
	{
		id: 'olandstok',
		latin: 'Dasiphora fruticosa',
		sv: 'Ölandstok',
		en: 'Shrubby cinquefoil',
		cat: 'shrub',
		form: 'shrub-mound',
		mature: { h: 0.9, w: 1.1 },
		growthRate: 4,
		evergreen: false,
		foliage: { spring: '#8faa72', summer: '#5c7a4c', autumn: '#a89a52', winter: null },
		bark: '#7a6248',
		bloom: { colour: '#f2d24a', months: [6, 7, 8, 9], size: 0.03 },
		needs: { sun: 'full', moisture: 'dry', zone: 7 },
		spacing: 0.8
	},
	{
		id: 'rosenrips',
		latin: 'Ribes sanguineum',
		sv: 'Rosenrips',
		en: 'Flowering currant',
		cat: 'shrub',
		form: 'shrub-mound',
		mature: { h: 2, w: 1.6 },
		growthRate: 4,
		evergreen: false,
		foliage: { spring: '#7fa855', summer: '#4a7440', autumn: '#b59440', winter: null },
		bark: '#6b5745',
		bloom: { colour: '#d4658a', months: [4, 5], size: 0.08 },
		needs: { sun: 'part', moisture: 'normal', zone: 4 },
		spacing: 1.4
	},
	{
		id: 'syrenbuddleja',
		latin: 'Buddleja davidii',
		sv: 'Syrenbuddleja',
		en: 'Butterfly bush',
		cat: 'shrub',
		form: 'shrub-mound',
		mature: { h: 2.2, w: 2 },
		growthRate: 3,
		evergreen: false,
		foliage: { spring: '#8a9f6a', summer: '#5f7a52', autumn: '#7a7a48', winter: null },
		bark: '#6f6050',
		bloom: { colour: '#8a5faf', months: [7, 8, 9], size: 0.2 },
		needs: { sun: 'full', moisture: 'normal', zone: 2 },
		spacing: 1.8
	},
	{
		id: 'lavendel',
		latin: 'Lavandula angustifolia',
		sv: 'Lavendel',
		en: 'Lavender',
		cat: 'shrub',
		form: 'shrub-mound',
		mature: { h: 0.45, w: 0.6 },
		growthRate: 2,
		evergreen: true,
		foliage: { spring: '#93a58f', summer: '#8fa08a', autumn: '#8a9b86', winter: '#7f9080' },
		bark: '#7a6f5c',
		bloom: { colour: '#7b6bb5', months: [6, 7, 8], size: 0.06 },
		needs: { sun: 'full', moisture: 'dry', zone: 3 },
		spacing: 0.4
	},
	{
		id: 'klematis',
		latin: 'Clematis viticella',
		sv: 'Italiensk klematis',
		en: 'Italian clematis',
		cat: 'climber',
		form: 'climber-on-support',
		mature: { h: 3.5, w: 1.2 },
		growthRate: 3,
		evergreen: false,
		foliage: { spring: '#7fa85c', summer: '#48733e', autumn: '#8a8548', winter: null },
		bark: '#6b5c4a',
		bloom: { colour: '#7a3f8f', months: [7, 8, 9], size: 0.08 },
		needs: { sun: 'part', moisture: 'moist', zone: 5 },
		spacing: 1
	},
	{
		id: 'kaprifol',
		latin: 'Lonicera caprifolium',
		sv: 'Kaprifol',
		en: 'Italian honeysuckle',
		cat: 'climber',
		form: 'climber-on-support',
		mature: { h: 5, w: 1.6 },
		growthRate: 4,
		evergreen: false,
		foliage: { spring: '#84a86a', summer: '#4f7548', autumn: '#a08f4a', winter: null },
		bark: '#6f5f4c',
		bloom: { colour: '#f2dcb2', months: [6, 7], size: 0.06 },
		fruit: { colour: '#d4472a', months: [8, 9] },
		needs: { sun: 'part', moisture: 'normal', zone: 4 },
		spacing: 1.2
	},
	{
		id: 'humle',
		latin: 'Humulus lupulus',
		sv: 'Humle',
		en: 'Hop',
		cat: 'climber',
		form: 'climber-on-support',
		mature: { h: 5, w: 1.2 },
		growthRate: 2,
		evergreen: false,
		foliage: { spring: '#8fb857', summer: '#5c8a3f', autumn: '#c2a83f', winter: null },
		bark: '#6f6248',
		fruit: { colour: '#c4cf8a', months: [8, 9] },
		needs: { sun: 'part', moisture: 'moist', zone: 6 },
		spacing: 1
	},
	{
		id: 'murgrona',
		latin: 'Hedera helix',
		sv: 'Murgröna',
		en: 'Common ivy',
		cat: 'climber',
		form: 'climber-on-support',
		mature: { h: 6, w: 1.5 },
		growthRate: 6,
		evergreen: true,
		foliage: { spring: '#43703f', summer: '#355f38', autumn: '#345c37', winter: '#325936' },
		bark: '#6b5a4a',
		fruit: { colour: '#2b2b33', months: [10, 11] },
		needs: { sun: 'shade', moisture: 'normal', zone: 3 },
		spacing: 1
	},
	{
		id: 'vildvin',
		latin: 'Parthenocissus quinquefolia',
		sv: 'Vildvin',
		en: 'Virginia creeper',
		cat: 'climber',
		form: 'climber-on-support',
		mature: { h: 8, w: 2 },
		growthRate: 4,
		evergreen: false,
		foliage: { spring: '#7fa855', summer: '#3f6b3a', autumn: '#b8261f', winter: null },
		bark: '#65553f',
		fruit: { colour: '#2f3a52', months: [9, 10] },
		needs: { sun: 'part', moisture: 'normal', zone: 5 },
		spacing: 1.5
	},
	{
		id: 'blaregn',
		latin: 'Wisteria sinensis',
		sv: 'Blåregn',
		en: 'Chinese wisteria',
		cat: 'climber',
		form: 'climber-on-support',
		mature: { h: 7, w: 2.5 },
		growthRate: 6,
		evergreen: false,
		foliage: { spring: '#93b862', summer: '#527d42', autumn: '#d2b845', winter: null },
		bark: '#6b5a45',
		bloom: { colour: '#8f8fc4', months: [5, 6], size: 0.25 },
		needs: { sun: 'full', moisture: 'normal', zone: 2 },
		spacing: 2
	},
	{
		id: 'klatterhortensia',
		latin: 'Hydrangea petiolaris',
		sv: 'Klätterhortensia',
		en: 'Climbing hydrangea',
		cat: 'climber',
		form: 'climber-on-support',
		mature: { h: 6, w: 2 },
		growthRate: 7,
		evergreen: false,
		foliage: { spring: '#7fb055', summer: '#43703c', autumn: '#c9b04a', winter: null },
		bark: '#75634f',
		bloom: { colour: '#f4efe2', months: [6, 7], size: 0.14 },
		needs: { sun: 'shade', moisture: 'moist', zone: 5 },
		spacing: 1.5
	},
	{
		id: 'klatterros',
		latin: 'Rosa x kordesii',
		sv: 'Klätterros',
		en: 'Climbing rose',
		cat: 'climber',
		form: 'climber-on-support',
		mature: { h: 3.5, w: 1.5 },
		growthRate: 3,
		evergreen: false,
		foliage: { spring: '#7fa855', summer: '#436f3a', autumn: '#b5934a', winter: null },
		bark: '#6f5c46',
		bloom: { colour: '#c8323f', months: [6, 7, 8], size: 0.09 },
		fruit: { colour: '#c8482a', months: [9, 10] },
		needs: { sun: 'full', moisture: 'normal', zone: 4 },
		spacing: 1.2
	},
	{
		id: 'funkia',
		latin: 'Hosta sieboldiana',
		sv: 'Daggfunkia',
		en: 'Hosta',
		cat: 'perennial',
		form: 'perennial-clump',
		mature: { h: 0.7, w: 1 },
		growthRate: 3,
		evergreen: false,
		foliage: { spring: '#7f9a7a', summer: '#6b8a72', autumn: '#c2b45c', winter: null },
		bark: '#5c7040',
		bloom: { colour: '#c9bcd8', months: [7, 8], size: 0.05 },
		needs: { sun: 'shade', moisture: 'moist', zone: 6 },
		spacing: 0.8
	},
	{
		id: 'daglilja',
		latin: 'Hemerocallis hybrida',
		sv: 'Daglilja',
		en: 'Daylily',
		cat: 'perennial',
		form: 'perennial-clump',
		mature: { h: 0.8, w: 0.7 },
		growthRate: 2,
		evergreen: false,
		foliage: { spring: '#7fa855', summer: '#5c8442', autumn: '#b5a24a', winter: null },
		bark: '#5c7040',
		bloom: { colour: '#e08a2a', months: [7, 8], size: 0.11 },
		needs: { sun: 'full', moisture: 'normal', zone: 6 },
		spacing: 0.6
	},
	{
		id: 'pion',
		latin: 'Paeonia lactiflora',
		sv: 'Luktpion',
		en: 'Chinese peony',
		cat: 'perennial',
		form: 'perennial-clump',
		mature: { h: 0.9, w: 0.9 },
		growthRate: 4,
		evergreen: false,
		foliage: { spring: '#6f8f52', summer: '#4a7040', autumn: '#a85a3a', winter: null },
		bark: '#5c7040',
		bloom: { colour: '#e8a8bc', months: [6], size: 0.14 },
		needs: { sun: 'full', moisture: 'normal', zone: 5 },
		spacing: 0.9
	},
	{
		id: 'lupin',
		latin: 'Lupinus polyphyllus',
		sv: 'Blomsterlupin',
		en: 'Garden lupin',
		cat: 'perennial',
		form: 'perennial-clump',
		mature: { h: 1, w: 0.6 },
		growthRate: 2,
		evergreen: false,
		foliage: { spring: '#7fa06a', summer: '#5f8455', autumn: '#8a8a4a', winter: null },
		bark: '#5c7040',
		bloom: { colour: '#7a6ab5', months: [6, 7], size: 0.3 },
		needs: { sun: 'full', moisture: 'normal', zone: 7 },
		spacing: 0.5
	},
	{
		id: 'daggkapa',
		latin: 'Alchemilla mollis',
		sv: 'Jättedaggkåpa',
		en: 'Ladys mantle',
		cat: 'perennial',
		form: 'perennial-clump',
		mature: { h: 0.45, w: 0.6 },
		growthRate: 2,
		evergreen: false,
		foliage: { spring: '#8fa87a', summer: '#7a9464', autumn: '#b5a85c', winter: null },
		bark: '#5c7040',
		bloom: { colour: '#c9cf5f', months: [6, 7, 8], size: 0.12 },
		needs: { sun: 'part', moisture: 'normal', zone: 6 },
		spacing: 0.5
	},
	{
		id: 'rudbeckia',
		latin: 'Rudbeckia fulgida',
		sv: 'Strålrudbeckia',
		en: 'Black-eyed Susan',
		cat: 'perennial',
		form: 'perennial-clump',
		mature: { h: 0.7, w: 0.6 },
		growthRate: 2,
		evergreen: false,
		foliage: { spring: '#6f8f4f', summer: '#4f7540', autumn: '#8a7f42', winter: null },
		bark: '#5c7040',
		bloom: { colour: '#e8b32a', months: [8, 9, 10], size: 0.07 },
		needs: { sun: 'full', moisture: 'normal', zone: 5 },
		spacing: 0.5
	},
	{
		id: 'solhatt',
		latin: 'Echinacea purpurea',
		sv: 'Röd solhatt',
		en: 'Purple coneflower',
		cat: 'perennial',
		form: 'perennial-clump',
		mature: { h: 0.9, w: 0.5 },
		growthRate: 2,
		evergreen: false,
		foliage: { spring: '#6f8f52', summer: '#527a44', autumn: '#8a7a42', winter: null },
		bark: '#5c7040',
		bloom: { colour: '#c96a8a', months: [7, 8, 9], size: 0.09 },
		needs: { sun: 'full', moisture: 'normal', zone: 4 },
		spacing: 0.5
	},
	{
		id: 'hostflox',
		latin: 'Phlox paniculata',
		sv: 'Höstflox',
		en: 'Garden phlox',
		cat: 'perennial',
		form: 'perennial-clump',
		mature: { h: 1, w: 0.6 },
		growthRate: 2,
		evergreen: false,
		foliage: { spring: '#6f9450', summer: '#4f7a42', autumn: '#8a8544', winter: null },
		bark: '#5c7040',
		bloom: { colour: '#d4739c', months: [7, 8, 9], size: 0.14 },
		needs: { sun: 'part', moisture: 'moist', zone: 6 },
		spacing: 0.5
	},
	{
		id: 'stormhatt',
		latin: 'Aconitum napellus',
		sv: 'Äkta stormhatt',
		en: 'Monkshood',
		cat: 'perennial',
		form: 'perennial-clump',
		mature: { h: 1.2, w: 0.5 },
		growthRate: 3,
		evergreen: false,
		foliage: { spring: '#5f8a45', summer: '#3f6b3a', autumn: '#7a7a40', winter: null },
		bark: '#5c7040',
		bloom: { colour: '#4a4f9c', months: [7, 8], size: 0.25 },
		needs: { sun: 'part', moisture: 'moist', zone: 6 },
		spacing: 0.5
	},
	{
		id: 'riddarsporre',
		latin: 'Delphinium elatum',
		sv: 'Riddarsporre',
		en: 'Delphinium',
		cat: 'perennial',
		form: 'perennial-clump',
		mature: { h: 1.6, w: 0.6 },
		growthRate: 2,
		evergreen: false,
		foliage: { spring: '#6f9450', summer: '#527d44', autumn: '#8a8244', winter: null },
		bark: '#5c7040',
		bloom: { colour: '#3f5fb5', months: [6, 7], size: 0.4 },
		needs: { sun: 'full', moisture: 'moist', zone: 6 },
		spacing: 0.6
	},
	{
		id: 'akleja',
		latin: 'Aquilegia vulgaris',
		sv: 'Akleja',
		en: 'Columbine',
		cat: 'perennial',
		form: 'perennial-clump',
		mature: { h: 0.7, w: 0.4 },
		growthRate: 2,
		evergreen: false,
		foliage: { spring: '#8fa87f', summer: '#6f8f6a', autumn: '#a89a5c', winter: null },
		bark: '#5c7040',
		bloom: { colour: '#6f4f9c', months: [5, 6], size: 0.05 },
		needs: { sun: 'part', moisture: 'normal', zone: 6 },
		spacing: 0.35
	},
	{
		id: 'praktlysing',
		latin: 'Lysimachia punctata',
		sv: 'Praktlysing',
		en: 'Dotted loosestrife',
		cat: 'perennial',
		form: 'perennial-clump',
		mature: { h: 0.9, w: 0.6 },
		growthRate: 2,
		evergreen: false,
		foliage: { spring: '#7f9f52', summer: '#5c8442', autumn: '#a89040', winter: null },
		bark: '#5c7040',
		bloom: { colour: '#f2cf2a', months: [6, 7, 8], size: 0.04 },
		needs: { sun: 'part', moisture: 'moist', zone: 6 },
		spacing: 0.5
	},
	{
		id: 'karleksort',
		latin: 'Hylotelephium telephium',
		sv: 'Kärleksört',
		en: 'Orpine',
		cat: 'perennial',
		form: 'perennial-clump',
		mature: { h: 0.55, w: 0.5 },
		growthRate: 2,
		evergreen: false,
		foliage: { spring: '#9fb59a', summer: '#8aa88f', autumn: '#a89a72', winter: null },
		bark: '#5c7040',
		bloom: { colour: '#c47a8a', months: [8, 9, 10], size: 0.12 },
		needs: { sun: 'full', moisture: 'dry', zone: 6 },
		spacing: 0.45
	},
	{
		id: 'rolleka',
		latin: 'Achillea millefolium',
		sv: 'Rölleka',
		en: 'Yarrow',
		cat: 'perennial',
		form: 'perennial-clump',
		mature: { h: 0.7, w: 0.5 },
		growthRate: 2,
		evergreen: false,
		foliage: { spring: '#8fa87a', summer: '#7a9469', autumn: '#9a9a5c', winter: null },
		bark: '#5c7040',
		bloom: { colour: '#e09a3a', months: [6, 7, 8], size: 0.1 },
		needs: { sun: 'full', moisture: 'dry', zone: 7 },
		spacing: 0.45
	},
	{
		id: 'salvia',
		latin: 'Salvia nemorosa',
		sv: 'Stäppsalvia',
		en: 'Woodland sage',
		cat: 'perennial',
		form: 'perennial-clump',
		mature: { h: 0.6, w: 0.5 },
		growthRate: 2,
		evergreen: false,
		foliage: { spring: '#7f9a6a', summer: '#647f57', autumn: '#8a8a52', winter: null },
		bark: '#5c7040',
		bloom: { colour: '#5f4a9c', months: [6, 7, 8], size: 0.18 },
		needs: { sun: 'full', moisture: 'dry', zone: 4 },
		spacing: 0.4
	},
	{
		id: 'kattmynta',
		latin: 'Nepeta x faassenii',
		sv: 'Kantnepeta',
		en: 'Catmint',
		cat: 'perennial',
		form: 'perennial-clump',
		mature: { h: 0.5, w: 0.7 },
		growthRate: 2,
		evergreen: false,
		foliage: { spring: '#9fb096', summer: '#8aa287', autumn: '#94966f', winter: null },
		bark: '#5c7040',
		bloom: { colour: '#8f8fc4', months: [6, 7, 8, 9], size: 0.15 },
		needs: { sun: 'full', moisture: 'dry', zone: 5 },
		spacing: 0.5
	},
	{
		id: 'gullris',
		latin: 'Solidago canadensis',
		sv: 'Kanadensiskt gullris',
		en: 'Canada goldenrod',
		cat: 'perennial',
		form: 'perennial-clump',
		mature: { h: 1.3, w: 0.7 },
		growthRate: 2,
		evergreen: false,
		foliage: { spring: '#6f9450', summer: '#527d42', autumn: '#a89040', winter: null },
		bark: '#5c7040',
		bloom: { colour: '#e8c42a', months: [8, 9], size: 0.2 },
		needs: { sun: 'full', moisture: 'normal', zone: 6 },
		spacing: 0.6
	},
	{
		id: 'hostaster',
		latin: 'Symphyotrichum novi-belgii',
		sv: 'Höstaster',
		en: 'Michaelmas daisy',
		cat: 'perennial',
		form: 'perennial-clump',
		mature: { h: 1, w: 0.7 },
		growthRate: 2,
		evergreen: false,
		foliage: { spring: '#6f9450', summer: '#4f7a42', autumn: '#7a8548', winter: null },
		bark: '#5c7040',
		bloom: { colour: '#8f7fc4', months: [9, 10], size: 0.05 },
		needs: { sun: 'full', moisture: 'normal', zone: 5 },
		spacing: 0.5
	},
	{
		id: 'julros',
		latin: 'Helleborus niger',
		sv: 'Julros',
		en: 'Christmas rose',
		cat: 'perennial',
		form: 'perennial-clump',
		mature: { h: 0.35, w: 0.4 },
		growthRate: 4,
		evergreen: true,
		foliage: { spring: '#3f6b40', summer: '#375f3c', autumn: '#365d3b', winter: '#345a39' },
		bark: '#5c7040',
		bloom: { colour: '#f4f0e6', months: [1, 2, 3, 12], size: 0.07 },
		needs: { sun: 'shade', moisture: 'normal', zone: 3 },
		spacing: 0.35
	},
	{
		id: 'hostanemon',
		latin: 'Anemone hupehensis',
		sv: 'Höstanemon',
		en: 'Japanese anemone',
		cat: 'perennial',
		form: 'perennial-clump',
		mature: { h: 1, w: 0.6 },
		growthRate: 3,
		evergreen: false,
		foliage: { spring: '#5f8a45', summer: '#42703c', autumn: '#7a7f44', winter: null },
		bark: '#5c7040',
		bloom: { colour: '#e2b0c4', months: [8, 9, 10], size: 0.06 },
		needs: { sun: 'part', moisture: 'moist', zone: 3 },
		spacing: 0.5
	},
	{
		id: 'bergenia',
		latin: 'Bergenia cordifolia',
		sv: 'Hjärtbergenia',
		en: 'Elephant ears',
		cat: 'perennial',
		form: 'perennial-clump',
		mature: { h: 0.4, w: 0.6 },
		growthRate: 3,
		evergreen: true,
		foliage: { spring: '#4a7042', summer: '#3f6b3f', autumn: '#8a4a3a', winter: '#6f3a35' },
		bark: '#5c7040',
		bloom: { colour: '#d47a9c', months: [4, 5], size: 0.1 },
		needs: { sun: 'part', moisture: 'normal', zone: 6 },
		spacing: 0.45
	},
	{
		id: 'lojtnantshjarta',
		latin: 'Lamprocapnos spectabilis',
		sv: 'Löjtnantshjärta',
		en: 'Bleeding heart',
		cat: 'perennial',
		form: 'perennial-clump',
		mature: { h: 0.8, w: 0.7 },
		growthRate: 3,
		evergreen: false,
		foliage: { spring: '#8fa87f', summer: '#7a9469', autumn: '#c2b45c', winter: null },
		bark: '#5c7040',
		bloom: { colour: '#e08aaa', months: [5, 6], size: 0.04 },
		needs: { sun: 'part', moisture: 'moist', zone: 6 },
		spacing: 0.6
	},
	{
		id: 'prastkrage',
		latin: 'Leucanthemum x superbum',
		sv: 'Jätteprästkrage',
		en: 'Shasta daisy',
		cat: 'perennial',
		form: 'perennial-clump',
		mature: { h: 0.8, w: 0.5 },
		growthRate: 2,
		evergreen: false,
		foliage: { spring: '#5f8a45', summer: '#4a7540', autumn: '#7a7f44', winter: null },
		bark: '#5c7040',
		bloom: { colour: '#f7f4ea', months: [6, 7, 8], size: 0.08 },
		needs: { sun: 'full', moisture: 'normal', zone: 6 },
		spacing: 0.45
	},
	{
		id: 'iris',
		latin: 'Iris sibirica',
		sv: 'Strandiris',
		en: 'Siberian iris',
		cat: 'perennial',
		form: 'grass-tuft',
		mature: { h: 0.9, w: 0.6 },
		growthRate: 3,
		evergreen: false,
		foliage: { spring: '#6f9455', summer: '#557f47', autumn: '#a89a52', winter: null },
		bark: '#5c7040',
		bloom: { colour: '#5a5fb5', months: [6], size: 0.1 },
		needs: { sun: 'full', moisture: 'moist', zone: 6 },
		spacing: 0.5
	},
	{
		id: 'strutbraken',
		latin: 'Matteuccia struthiopteris',
		sv: 'Strutbräken',
		en: 'Ostrich fern',
		cat: 'fern',
		form: 'grass-tuft',
		mature: { h: 1.2, w: 0.9 },
		growthRate: 3,
		evergreen: false,
		foliage: { spring: '#7fb55f', summer: '#4f8244', autumn: '#b59a48', winter: null },
		bark: '#5c7040',
		needs: { sun: 'shade', moisture: 'moist', zone: 7 },
		spacing: 0.8
	},
	{
		id: 'trajon',
		latin: 'Dryopteris filix-mas',
		sv: 'Träjon',
		en: 'Male fern',
		cat: 'fern',
		form: 'perennial-clump',
		mature: { h: 0.9, w: 0.9 },
		growthRate: 3,
		evergreen: false,
		foliage: { spring: '#6f9a52', summer: '#42703c', autumn: '#8a8548', winter: null },
		bark: '#5c7040',
		needs: { sun: 'shade', moisture: 'moist', zone: 6 },
		spacing: 0.7
	},
	{
		id: 'tuvror',
		latin: 'Calamagrostis x acutiflora',
		sv: 'Tuvrör',
		en: 'Feather reed grass',
		cat: 'grass',
		form: 'grass-tuft',
		mature: { h: 1.6, w: 0.6 },
		growthRate: 2,
		evergreen: false,
		foliage: { spring: '#7fa855', summer: '#5f8a47', autumn: '#c9b06a', winter: null },
		bark: '#5c7040',
		bloom: { colour: '#d8c68f', months: [6, 7, 8, 9], size: 0.3 },
		needs: { sun: 'full', moisture: 'normal', zone: 5 },
		spacing: 0.6
	},
	{
		id: 'glansmiskantus',
		latin: 'Miscanthus sinensis var. purpurascens',
		sv: 'Glansmiskantus',
		en: 'Flame grass',
		cat: 'grass',
		form: 'grass-tuft',
		mature: { h: 1.5, w: 0.8 },
		growthRate: 3,
		evergreen: false,
		foliage: { spring: '#7fa855', summer: '#5f8a52', autumn: '#c26a3a', winter: null },
		bark: '#5c7040',
		bloom: { colour: '#e2d2b5', months: [8, 9, 10], size: 0.2 },
		needs: { sun: 'full', moisture: 'normal', zone: 4 },
		spacing: 0.8
	},
	{
		id: 'blatatel',
		latin: 'Molinia caerulea',
		sv: 'Blåtåtel',
		en: 'Purple moor grass',
		cat: 'grass',
		form: 'grass-tuft',
		mature: { h: 1.2, w: 0.6 },
		growthRate: 3,
		evergreen: false,
		foliage: { spring: '#7fa855', summer: '#5c8a4f', autumn: '#d2b25c', winter: null },
		bark: '#5c7040',
		bloom: { colour: '#8f8a72', months: [7, 8, 9], size: 0.25 },
		needs: { sun: 'part', moisture: 'moist', zone: 6 },
		spacing: 0.6
	},
	{
		id: 'blasvingel',
		latin: 'Festuca glauca',
		sv: 'Blåsvingel',
		en: 'Blue fescue',
		cat: 'grass',
		form: 'grass-tuft',
		mature: { h: 0.3, w: 0.35 },
		growthRate: 2,
		evergreen: true,
		foliage: { spring: '#93a8b0', summer: '#8aa0aa', autumn: '#8a9aa0', winter: '#7f9098' },
		bark: '#5c7040',
		bloom: { colour: '#c9c2a0', months: [6, 7], size: 0.08 },
		needs: { sun: 'full', moisture: 'dry', zone: 5 },
		spacing: 0.3
	},
	{
		id: 'japanskstarr',
		latin: 'Carex morrowii',
		sv: 'Japansk starr',
		en: 'Japanese sedge',
		cat: 'grass',
		form: 'grass-tuft',
		mature: { h: 0.4, w: 0.5 },
		growthRate: 2,
		evergreen: true,
		foliage: { spring: '#6f9455', summer: '#5c8a4c', autumn: '#5a8549', winter: '#557f45' },
		bark: '#5c7040',
		needs: { sun: 'part', moisture: 'normal', zone: 3 },
		spacing: 0.4
	},
	{
		id: 'vintergrona',
		latin: 'Vinca minor',
		sv: 'Vintergröna',
		en: 'Lesser periwinkle',
		cat: 'groundcover',
		form: 'groundcover-mat',
		mature: { h: 0.2, w: 0.6 },
		growthRate: 3,
		evergreen: true,
		foliage: { spring: '#3f6b40', summer: '#35603a', autumn: '#345d39', winter: '#325937' },
		bark: '#5c7040',
		bloom: { colour: '#7f8fc4', months: [4, 5, 6], size: 0.03 },
		needs: { sun: 'shade', moisture: 'normal', zone: 4 },
		spacing: 0.35
	},
	{
		id: 'krypoxbar',
		latin: 'Cotoneaster dammeri',
		sv: 'Krypoxbär',
		en: 'Bearberry cotoneaster',
		cat: 'groundcover',
		form: 'groundcover-mat',
		mature: { h: 0.25, w: 0.9 },
		growthRate: 3,
		evergreen: true,
		foliage: { spring: '#456f42', summer: '#3a643c', autumn: '#8a4a35', winter: '#4a5f3f' },
		bark: '#65543f',
		bloom: { colour: '#f2ece0', months: [6], size: 0.015 },
		fruit: { colour: '#c8332a', months: [9, 10, 11] },
		needs: { sun: 'part', moisture: 'normal', zone: 4 },
		spacing: 0.5
	},
	{
		id: 'gullgrona',
		latin: 'Waldsteinia ternata',
		sv: 'Gullgröna',
		en: 'Barren strawberry',
		cat: 'groundcover',
		form: 'groundcover-mat',
		mature: { h: 0.18, w: 0.5 },
		growthRate: 3,
		evergreen: true,
		foliage: { spring: '#5c8a44', summer: '#4a7540', autumn: '#48723e', winter: '#446b3c' },
		bark: '#5c7040',
		bloom: { colour: '#e8c42a', months: [4, 5], size: 0.02 },
		needs: { sun: 'shade', moisture: 'normal', zone: 5 },
		spacing: 0.3
	},
	{
		id: 'flocknava',
		latin: 'Geranium macrorrhizum',
		sv: 'Flocknäva',
		en: 'Bigroot geranium',
		cat: 'groundcover',
		form: 'groundcover-mat',
		mature: { h: 0.35, w: 0.6 },
		growthRate: 2,
		evergreen: false,
		foliage: { spring: '#7f9f5c', summer: '#5f8a4c', autumn: '#c25f3a', winter: null },
		bark: '#5c7040',
		bloom: { colour: '#d47a9c', months: [5, 6, 7], size: 0.03 },
		needs: { sun: 'shade', moisture: 'normal', zone: 6 },
		spacing: 0.4
	},
	{
		id: 'backtimjan',
		latin: 'Thymus serpyllum',
		sv: 'Backtimjan',
		en: 'Creeping thyme',
		cat: 'groundcover',
		form: 'groundcover-mat',
		mature: { h: 0.1, w: 0.4 },
		growthRate: 2,
		evergreen: true,
		foliage: { spring: '#6f8a5c', summer: '#5f7f52', autumn: '#5c7a50', winter: '#57734c' },
		bark: '#6f6248',
		bloom: { colour: '#b06a9c', months: [6, 7], size: 0.02 },
		needs: { sun: 'full', moisture: 'dry', zone: 6 },
		spacing: 0.25
	},
	{
		id: 'liljekonvalj',
		latin: 'Convallaria majalis',
		sv: 'Liljekonvalj',
		en: 'Lily of the valley',
		cat: 'groundcover',
		form: 'groundcover-mat',
		mature: { h: 0.25, w: 0.4 },
		growthRate: 3,
		evergreen: false,
		foliage: { spring: '#6f9a52', summer: '#4f7f44', autumn: '#b5a04a', winter: null },
		bark: '#5c7040',
		bloom: { colour: '#f7f4ec', months: [5, 6], size: 0.02 },
		fruit: { colour: '#c8332a', months: [8, 9] },
		needs: { sun: 'shade', moisture: 'normal', zone: 7 },
		spacing: 0.25
	},
	{
		id: 'snodroppe',
		latin: 'Galanthus nivalis',
		sv: 'Snödroppe',
		en: 'Snowdrop',
		cat: 'bulb',
		form: 'bulb-cluster',
		mature: { h: 0.15, w: 0.12 },
		growthRate: 1,
		evergreen: false,
		foliage: { spring: '#7f9a72', summer: '#6f8a66', autumn: '#8a8a5c', winter: null },
		bark: '#5c7040',
		bloom: { colour: '#f7f7f0', months: [2, 3, 4], size: 0.025 },
		needs: { sun: 'part', moisture: 'normal', zone: 6 },
		spacing: 0.1
	},
	{
		id: 'vintergack',
		latin: 'Eranthis hyemalis',
		sv: 'Vintergäck',
		en: 'Winter aconite',
		cat: 'bulb',
		form: 'bulb-cluster',
		mature: { h: 0.12, w: 0.12 },
		growthRate: 1,
		evergreen: false,
		foliage: { spring: '#6f9a52', summer: '#5f8a4c', autumn: '#8a8a52', winter: null },
		bark: '#5c7040',
		bloom: { colour: '#f2cf2a', months: [2, 3], size: 0.025 },
		needs: { sun: 'part', moisture: 'normal', zone: 5 },
		spacing: 0.1
	},
	{
		id: 'krokus',
		latin: 'Crocus vernus',
		sv: 'Vårkrokus',
		en: 'Spring crocus',
		cat: 'bulb',
		form: 'bulb-cluster',
		mature: { h: 0.13, w: 0.1 },
		growthRate: 1,
		evergreen: false,
		foliage: { spring: '#6f9a5c', summer: '#5f8a52', autumn: '#8a8a52', winter: null },
		bark: '#5c7040',
		bloom: { colour: '#8f6ab5', months: [3, 4], size: 0.04 },
		needs: { sun: 'full', moisture: 'normal', zone: 6 },
		spacing: 0.08
	},
	{
		id: 'pasklilja',
		latin: 'Narcissus pseudonarcissus',
		sv: 'Påsklilja',
		en: 'Daffodil',
		cat: 'bulb',
		form: 'bulb-cluster',
		mature: { h: 0.35, w: 0.2 },
		growthRate: 1,
		evergreen: false,
		foliage: { spring: '#6f9a62', summer: '#5f8a55', autumn: '#8a8a52', winter: null },
		bark: '#5c7040',
		bloom: { colour: '#f2c22a', months: [4, 5], size: 0.07 },
		needs: { sun: 'full', moisture: 'normal', zone: 6 },
		spacing: 0.12
	},
	{
		id: 'tulpan',
		latin: 'Tulipa gesneriana',
		sv: 'Trädgårdstulpan',
		en: 'Garden tulip',
		cat: 'bulb',
		form: 'bulb-cluster',
		mature: { h: 0.45, w: 0.18 },
		growthRate: 1,
		evergreen: false,
		foliage: { spring: '#8fa89a', summer: '#7f9a8a', autumn: '#8a8a5c', winter: null },
		bark: '#5c7040',
		bloom: { colour: '#c8323f', months: [4, 5], size: 0.08 },
		needs: { sun: 'full', moisture: 'normal', zone: 5 },
		spacing: 0.12
	},
	{
		id: 'blastjarna',
		latin: 'Scilla siberica',
		sv: 'Rysk blåstjärna',
		en: 'Siberian squill',
		cat: 'bulb',
		form: 'bulb-cluster',
		mature: { h: 0.14, w: 0.12 },
		growthRate: 1,
		evergreen: false,
		foliage: { spring: '#5f8a4c', summer: '#557f47', autumn: '#7f8a52', winter: null },
		bark: '#5c7040',
		bloom: { colour: '#3f6ac4', months: [3, 4], size: 0.03 },
		needs: { sun: 'part', moisture: 'normal', zone: 6 },
		spacing: 0.08
	},
	{
		id: 'parlhyacint',
		latin: 'Muscari armeniacum',
		sv: 'Armenisk pärlhyacint',
		en: 'Grape hyacinth',
		cat: 'bulb',
		form: 'bulb-cluster',
		mature: { h: 0.2, w: 0.12 },
		growthRate: 1,
		evergreen: false,
		foliage: { spring: '#5f8a4c', summer: '#557f47', autumn: '#7f8a52', winter: null },
		bark: '#5c7040',
		bloom: { colour: '#3f4f9c', months: [4, 5], size: 0.035 },
		needs: { sun: 'full', moisture: 'normal', zone: 5 },
		spacing: 0.08
	},
	{
		id: 'aronia',
		latin: 'Aronia melanocarpa',
		sv: 'Svartaronia',
		en: 'Black chokeberry',
		cat: 'edible',
		form: 'shrub-mound',
		mature: { h: 2, w: 1.8 },
		growthRate: 5,
		evergreen: false,
		foliage: { spring: '#7fa855', summer: '#436f3c', autumn: '#c8322a', winter: null },
		bark: '#65543f',
		bloom: { colour: '#f4f0e4', months: [5, 6], size: 0.05 },
		fruit: { colour: '#2b2233', months: [8, 9] },
		needs: { sun: 'full', moisture: 'normal', zone: 6 },
		spacing: 1.5
	},
	{
		id: 'rabarber',
		latin: 'Rheum rhabarbarum',
		sv: 'Rabarber',
		en: 'Rhubarb',
		cat: 'edible',
		form: 'perennial-clump',
		mature: { h: 1, w: 1.2 },
		growthRate: 3,
		evergreen: false,
		foliage: { spring: '#5f8a44', summer: '#47703c', autumn: '#8a7a40', winter: null },
		bark: '#a8422f',
		bloom: { colour: '#f0ead4', months: [6], size: 0.3 },
		needs: { sun: 'full', moisture: 'moist', zone: 7 },
		spacing: 1.2
	},
	{
		id: 'jordgubbar',
		latin: 'Fragaria x ananassa',
		sv: 'Jordgubbar',
		en: 'Garden strawberry',
		cat: 'edible',
		form: 'groundcover-mat',
		mature: { h: 0.25, w: 0.35 },
		growthRate: 1,
		evergreen: false,
		foliage: { spring: '#5f8a44', summer: '#4f7a40', autumn: '#a85f3a', winter: null },
		bark: '#5c7040',
		bloom: { colour: '#f7f4ea', months: [5, 6], size: 0.025 },
		fruit: { colour: '#c8262a', months: [6, 7] },
		needs: { sun: 'full', moisture: 'normal', zone: 6 },
		spacing: 0.3
	},
	{
		id: 'svartvinbar',
		latin: 'Ribes nigrum',
		sv: 'Svarta vinbär',
		en: 'Blackcurrant',
		cat: 'edible',
		form: 'shrub-mound',
		mature: { h: 1.5, w: 1.4 },
		growthRate: 4,
		evergreen: false,
		foliage: { spring: '#7fa855', summer: '#4a7540', autumn: '#b59440', winter: null },
		bark: '#6b5745',
		bloom: { colour: '#c9c48a', months: [5], size: 0.02 },
		fruit: { colour: '#241f2b', months: [7, 8] },
		needs: { sun: 'part', moisture: 'moist', zone: 7 },
		spacing: 1.4
	},
	{
		id: 'rodvinbar',
		latin: 'Ribes rubrum',
		sv: 'Röda vinbär',
		en: 'Redcurrant',
		cat: 'edible',
		form: 'shrub-mound',
		mature: { h: 1.4, w: 1.3 },
		growthRate: 4,
		evergreen: false,
		foliage: { spring: '#7fa855', summer: '#4d7840', autumn: '#c2a04a', winter: null },
		bark: '#6b5745',
		bloom: { colour: '#c9c48a', months: [5], size: 0.02 },
		fruit: { colour: '#c8262a', months: [7, 8] },
		needs: { sun: 'part', moisture: 'normal', zone: 6 },
		spacing: 1.3
	},
	{
		id: 'krusbar',
		latin: 'Ribes uva-crispa',
		sv: 'Krusbär',
		en: 'Gooseberry',
		cat: 'edible',
		form: 'shrub-mound',
		mature: { h: 1.2, w: 1.2 },
		growthRate: 4,
		evergreen: false,
		foliage: { spring: '#7fa855', summer: '#4f7a42', autumn: '#b59440', winter: null },
		bark: '#6b5745',
		bloom: { colour: '#c9c48a', months: [5], size: 0.015 },
		fruit: { colour: '#a8b25c', months: [7, 8] },
		needs: { sun: 'full', moisture: 'normal', zone: 6 },
		spacing: 1.2
	},
	{
		id: 'hallon',
		latin: 'Rubus idaeus',
		sv: 'Hallon',
		en: 'Raspberry',
		cat: 'edible',
		form: 'multi-stem',
		mature: { h: 1.8, w: 0.8 },
		growthRate: 2,
		evergreen: false,
		foliage: { spring: '#7fa855', summer: '#4f7a44', autumn: '#a89040', winter: null },
		bark: '#8a7a62',
		bloom: { colour: '#f2eee2', months: [6], size: 0.02 },
		fruit: { colour: '#c23a52', months: [7, 8] },
		needs: { sun: 'part', moisture: 'moist', zone: 7 },
		spacing: 0.6
	},
	{
		id: 'potatis',
		latin: 'Solanum tuberosum',
		sv: 'Potatis',
		en: 'Potato',
		cat: 'edible',
		form: 'perennial-clump',
		mature: { h: 0.6, w: 0.5 },
		growthRate: 1,
		evergreen: false,
		foliage: { spring: '#5f8a44', summer: '#4a7540', autumn: '#8a8548', winter: null },
		bark: '#5c7040',
		bloom: { colour: '#e8e2ee', months: [6, 7], size: 0.03 },
		needs: { sun: 'full', moisture: 'normal', zone: 6 },
		spacing: 0.35
	},
	{
		id: 'gronkal',
		latin: 'Brassica oleracea var. sabellica',
		sv: 'Grönkål',
		en: 'Kale',
		cat: 'edible',
		form: 'perennial-clump',
		mature: { h: 0.7, w: 0.5 },
		growthRate: 1,
		evergreen: false,
		foliage: { spring: '#3f6b44', summer: '#365f3f', autumn: '#345c3e', winter: null },
		bark: '#5c7040',
		needs: { sun: 'full', moisture: 'moist', zone: 7 },
		spacing: 0.45
	},
	{
		id: 'vitkal',
		latin: 'Brassica oleracea var. capitata',
		sv: 'Vitkål',
		en: 'White cabbage',
		cat: 'edible',
		form: 'perennial-clump',
		mature: { h: 0.4, w: 0.5 },
		growthRate: 1,
		evergreen: false,
		foliage: { spring: '#8fa89a', summer: '#7f9a8f', autumn: '#7a948a', winter: null },
		bark: '#5c7040',
		needs: { sun: 'full', moisture: 'moist', zone: 6 },
		spacing: 0.5
	},
	{
		id: 'tomat',
		latin: 'Solanum lycopersicum',
		sv: 'Tomat',
		en: 'Tomato',
		cat: 'edible',
		form: 'perennial-clump',
		mature: { h: 1.5, w: 0.5 },
		growthRate: 1,
		evergreen: false,
		foliage: { spring: '#5f8a44', summer: '#4a7540', autumn: '#7a8244', winter: null },
		bark: '#5c7040',
		bloom: { colour: '#e8cf3a', months: [6, 7, 8], size: 0.02 },
		fruit: { colour: '#c8322a', months: [8, 9] },
		needs: { sun: 'full', moisture: 'moist', zone: 3 },
		spacing: 0.5
	},
	{
		id: 'squash',
		latin: 'Cucurbita pepo',
		sv: 'Squash',
		en: 'Courgette',
		cat: 'edible',
		form: 'groundcover-mat',
		mature: { h: 0.6, w: 1.4 },
		growthRate: 1,
		evergreen: false,
		foliage: { spring: '#5f8a44', summer: '#4f7a40', autumn: '#7a8244', winter: null },
		bark: '#5c7040',
		bloom: { colour: '#f2c22a', months: [7, 8], size: 0.09 },
		fruit: { colour: '#3f6b3a', months: [8, 9] },
		needs: { sun: 'full', moisture: 'moist', zone: 4 },
		spacing: 1
	},
	{
		id: 'bonor',
		latin: 'Phaseolus vulgaris',
		sv: 'Bönor',
		en: 'Green beans',
		cat: 'edible',
		form: 'grass-tuft',
		mature: { h: 0.6, w: 0.4 },
		growthRate: 1,
		evergreen: false,
		foliage: { spring: '#5f8a44', summer: '#4f7a42', autumn: '#8a8548', winter: null },
		bark: '#5c7040',
		bloom: { colour: '#f4f0e6', months: [7], size: 0.02 },
		fruit: { colour: '#6f9440', months: [8, 9] },
		needs: { sun: 'full', moisture: 'normal', zone: 4 },
		spacing: 0.3
	},
	{
		id: 'artor',
		latin: 'Pisum sativum',
		sv: 'Ärtor',
		en: 'Peas',
		cat: 'edible',
		form: 'grass-tuft',
		mature: { h: 1, w: 0.35 },
		growthRate: 1,
		evergreen: false,
		foliage: { spring: '#8fa89a', summer: '#7f9a82', autumn: '#8a8f5c', winter: null },
		bark: '#5c7040',
		bloom: { colour: '#f7f4ea', months: [6, 7], size: 0.02 },
		fruit: { colour: '#6f9440', months: [7, 8] },
		needs: { sun: 'full', moisture: 'normal', zone: 6 },
		spacing: 0.25
	},
	{
		id: 'morotter',
		latin: 'Daucus carota',
		sv: 'Morötter',
		en: 'Carrots',
		cat: 'edible',
		form: 'grass-tuft',
		mature: { h: 0.35, w: 0.25 },
		growthRate: 1,
		evergreen: false,
		foliage: { spring: '#5f8a44', summer: '#4f7f40', autumn: '#7a8244', winter: null },
		bark: '#5c7040',
		needs: { sun: 'full', moisture: 'normal', zone: 7 },
		spacing: 0.08
	},
	{
		id: 'sallad',
		latin: 'Lactuca sativa',
		sv: 'Sallad',
		en: 'Lettuce',
		cat: 'edible',
		form: 'perennial-clump',
		mature: { h: 0.25, w: 0.3 },
		growthRate: 1,
		evergreen: false,
		foliage: { spring: '#8fbb5c', summer: '#7fae52', autumn: '#7aa850', winter: null },
		bark: '#5c7040',
		needs: { sun: 'part', moisture: 'moist', zone: 7 },
		spacing: 0.25
	},
	{
		id: 'purjolok',
		latin: 'Allium ampeloprasum',
		sv: 'Purjolök',
		en: 'Leek',
		cat: 'edible',
		form: 'grass-tuft',
		mature: { h: 0.6, w: 0.25 },
		growthRate: 1,
		evergreen: false,
		foliage: { spring: '#7f9a8a', summer: '#6f8f7f', autumn: '#6a8a7a', winter: null },
		bark: '#5c7040',
		needs: { sun: 'full', moisture: 'moist', zone: 6 },
		spacing: 0.2
	},
	{
		id: 'dill',
		latin: 'Anethum graveolens',
		sv: 'Dill',
		en: 'Dill',
		cat: 'edible',
		form: 'grass-tuft',
		mature: { h: 0.9, w: 0.3 },
		growthRate: 1,
		evergreen: false,
		foliage: { spring: '#7fa87a', summer: '#6f9a6f', autumn: '#8a9a5c', winter: null },
		bark: '#5c7040',
		bloom: { colour: '#d8cf5c', months: [7, 8], size: 0.12 },
		needs: { sun: 'full', moisture: 'normal', zone: 6 },
		spacing: 0.25
	},
	{
		id: 'persilja',
		latin: 'Petroselinum crispum',
		sv: 'Persilja',
		en: 'Parsley',
		cat: 'edible',
		form: 'perennial-clump',
		mature: { h: 0.3, w: 0.3 },
		growthRate: 1,
		evergreen: false,
		foliage: { spring: '#4a7a3f', summer: '#42703c', autumn: '#406e3a', winter: null },
		bark: '#5c7040',
		needs: { sun: 'part', moisture: 'moist', zone: 6 },
		spacing: 0.25
	},
	{
		id: 'graslok',
		latin: 'Allium schoenoprasum',
		sv: 'Gräslök',
		en: 'Chives',
		cat: 'edible',
		form: 'grass-tuft',
		mature: { h: 0.35, w: 0.3 },
		growthRate: 2,
		evergreen: false,
		foliage: { spring: '#5f8a52', summer: '#4f7f4a', autumn: '#7a8a52', winter: null },
		bark: '#5c7040',
		bloom: { colour: '#b06a9c', months: [6, 7], size: 0.04 },
		needs: { sun: 'full', moisture: 'normal', zone: 8 },
		spacing: 0.25
	},
	{
		id: 'mynta',
		latin: 'Mentha x piperita',
		sv: 'Mynta',
		en: 'Peppermint',
		cat: 'edible',
		form: 'perennial-clump',
		mature: { h: 0.6, w: 0.6 },
		growthRate: 2,
		evergreen: false,
		foliage: { spring: '#5f8a4c', summer: '#4a7544', autumn: '#7a8a4c', winter: null },
		bark: '#5c7040',
		bloom: { colour: '#c4b0d4', months: [7, 8], size: 0.04 },
		needs: { sun: 'part', moisture: 'moist', zone: 6 },
		spacing: 0.4
	},
	{
		id: 'kryddsalvia',
		latin: 'Salvia officinalis',
		sv: 'Kryddsalvia',
		en: 'Common sage',
		cat: 'edible',
		form: 'shrub-mound',
		mature: { h: 0.5, w: 0.6 },
		growthRate: 2,
		evergreen: true,
		foliage: { spring: '#9aa89a', summer: '#8a9a8f', autumn: '#87968c', winter: '#7f8f85' },
		bark: '#7a6f5c',
		bloom: { colour: '#8f8fc4', months: [6, 7], size: 0.1 },
		needs: { sun: 'full', moisture: 'dry', zone: 3 },
		spacing: 0.5
	},
	{
		id: 'kryddtimjan',
		latin: 'Thymus vulgaris',
		sv: 'Kryddtimjan',
		en: 'Common thyme',
		cat: 'edible',
		form: 'shrub-mound',
		mature: { h: 0.3, w: 0.4 },
		growthRate: 2,
		evergreen: true,
		foliage: { spring: '#7f8f6a', summer: '#6f8560', autumn: '#6c825e', winter: '#657a58' },
		bark: '#6f6248',
		bloom: { colour: '#c48fb0', months: [6, 7], size: 0.03 },
		needs: { sun: 'full', moisture: 'dry', zone: 3 },
		spacing: 0.3
	},
	{
		id: 'havtorn',
		latin: 'Hippophae rhamnoides',
		sv: 'Havtorn',
		en: 'Sea buckthorn',
		cat: 'edible',
		form: 'shrub-mound',
		mature: { h: 3, w: 2.5 },
		growthRate: 5,
		evergreen: false,
		foliage: { spring: '#a8b5a0', summer: '#98a892', autumn: '#9aa07a', winter: null },
		bark: '#6f6252',
		fruit: { colour: '#e08a1f', months: [8, 9, 10] },
		needs: { sun: 'full', moisture: 'dry', zone: 7 },
		spacing: 2
	}
];

/** Used when a document names a species this build does not know. */
const FALLBACK: Species = {
	id: 'okand',
	latin: 'Planta',
	sv: 'Okänd växt',
	en: 'Unknown plant',
	cat: 'shrub',
	form: 'shrub-mound',
	mature: { h: 1.2, w: 1.2 },
	growthRate: 5,
	evergreen: false,
	foliage: { spring: '#8fb85f', summer: '#4f7a3e', autumn: '#b59440', winter: null },
	bark: '#6b5a48',
	needs: { sun: 'part', moisture: 'normal', zone: 5 },
	spacing: 1
};

const INDEX: ReadonlyMap<SpeciesId, Species> = new Map(SPECIES.map((s) => [s.id, s]));

export function species(id: SpeciesId): Species | undefined {
	return INDEX.get(id);
}

export function speciesOr(id: SpeciesId): Species {
	return INDEX.get(id) ?? FALLBACK;
}

function groupByCat(all: readonly Species[]): ReadonlyMap<PlantCat, readonly Species[]> {
	const m = new Map<PlantCat, Species[]>();
	for (const s of all) {
		const list = m.get(s.cat);
		if (list) list.push(s);
		else m.set(s.cat, [s]);
	}
	for (const list of m.values()) list.sort((a, b) => a.sv.localeCompare(b.sv, 'sv'));
	return m;
}

export const BY_CAT: ReadonlyMap<PlantCat, readonly Species[]> = groupByCat(SPECIES);

/** Strips diacritics so "vresros" finds "Vresros" and "hagg" finds "Hägg". */
function fold(s: string): string {
	return s
		.normalize('NFD')
		.replace(/[\u0300-\u036f]/g, '')
		.toLowerCase()
		.trim();
}

export function searchSpecies(q: string): Species[] {
	const needle = fold(q);
	if (needle === '') return [...SPECIES];
	const hits: { s: Species; rank: number }[] = [];
	for (const s of SPECIES) {
		const fields = [fold(s.sv), fold(s.en), fold(s.latin), fold(s.id)];
		let rank = -1;
		for (let i = 0; i < fields.length; i++) {
			if (fields[i].startsWith(needle)) {
				rank = i;
				break;
			}
			if (fields[i].includes(needle) && rank < 0) rank = i + fields.length;
		}
		if (rank >= 0) hits.push({ s, rank });
	}
	hits.sort((a, b) => a.rank - b.rank || a.s.sv.localeCompare(b.s.sv, 'sv'));
	return hits.map((h) => h.s);
}
